spring.application.name=farmVerseApplication
server.port=9696
# Database URL pointing to studentdb
spring.datasource.url=jdbc:postgresql://localhost:5432/farmdb

# Your PostgreSQL credentials (update these with your system's username and password)
spring.datasource.username=postgres
spring.datasource.password=Ashok@12345

# PostgreSQL Driver class
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
# 'update' will automatically create or update tables based on your Entity classes
spring.jpa.hibernate.ddl-auto=update

# Shows the SQL queries in the console (helpful for teaching/debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Database dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hugging Face API
huggingface.api.url=https://router.huggingface.co/v1/chat/completions
huggingface.api.key=YOUR_API_KEY_HERE
huggingface.model.id=meta-llama/Llama-3.1-8B-Instruct







